[package]
name = "mmry-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "mmry"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mmry-core = { path = "../mmry-core" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
